name: Spring Boot CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '16th-Oct-2025/**'

  pull_request:
    branches: [ "main" ]
    paths:
      - '16th-Oct-2025/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: |
        cd 16th-Oct-2025/SBSecurity
        mvn clean verify

    - name: Run tests
      run: mvn test
